// Generated by BUCKLESCRIPT VERSION 4.0.7, PLEASE EDIT WITH CARE
'use strict';

var Js_null_undefined = require("bs-platform/lib/js/js_null_undefined.js");
var ApolloServerExpress = require("apollo-server-express");

function createGraphQLExpressMiddleware(formatError, rootValue, context, logFunction, formatParams, validationRules, formatResponse, fieldResolver, debug, schema, param) {
  return ApolloServerExpress.graphqlExpress({
              schema: schema,
              formatError: Js_null_undefined.fromOption(formatError),
              rootValue: Js_null_undefined.fromOption(rootValue),
              context: Js_null_undefined.fromOption(context),
              logFunction: Js_null_undefined.fromOption(logFunction),
              formatParams: Js_null_undefined.fromOption(formatParams),
              validationRules: Js_null_undefined.fromOption(validationRules),
              formatResponse: Js_null_undefined.fromOption(formatResponse),
              fieldResolver: Js_null_undefined.fromOption(fieldResolver),
              debug: Js_null_undefined.fromOption(debug)
            });
}

function createGraphiQLExpressMiddleware(query, variables, operationName, result, endpointURL, param) {
  return ApolloServerExpress.graphiqlExpress({
              endpointURL: endpointURL,
              query: Js_null_undefined.fromOption(query),
              variables: Js_null_undefined.fromOption(variables),
              operationName: Js_null_undefined.fromOption(operationName),
              result: Js_null_undefined.fromOption(result)
            });
}

exports.createGraphQLExpressMiddleware = createGraphQLExpressMiddleware;
exports.createGraphiQLExpressMiddleware = createGraphiQLExpressMiddleware;
/* apollo-server-express Not a pure module */
